# Generated by Django 4.1.7 on 2023-03-14 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invocadore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, default=django.db.models.fields.NOT_PROVIDED, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=django.db.models.fields.NOT_PROVIDED, max_length=20, null=True)),
                ('nivel', models.IntegerField(blank=True, default=django.db.models.fields.NOT_PROVIDED, null=True)),
                ('vida', models.IntegerField(blank=True, default=django.db.models.fields.NOT_PROVIDED, null=True)),
                ('resistencia', models.IntegerField(blank=True, default=django.db.models.fields.NOT_PROVIDED, null=True)),
                ('fuerza', models.IntegerField(blank=True, default=django.db.models.fields.NOT_PROVIDED, null=True)),
                ('daño', models.FloatField(blank=True, default=django.db.models.fields.NOT_PROVIDED, null=True)),
                ('tipo', models.CharField(blank=True, default=django.db.models.fields.NOT_PROVIDED, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, default=django.db.models.fields.NOT_PROVIDED, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=django.db.models.fields.NOT_PROVIDED, null=True)),
                ('name', models.CharField(blank=True, default=django.db.models.fields.NOT_PROVIDED, max_length=20, null=True)),
                ('fk', models.ForeignKey(default=django.db.models.fields.NOT_PROVIDED, on_delete=django.db.models.deletion.CASCADE, to='app.invocadore')),
            ],
        ),
    ]
