# Generated by Django 4.1.7 on 2023-03-14 18:15

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invocadore',
            name='img',
            field=models.ImageField(default=django.db.models.fields.NOT_PROVIDED, null=True, upload_to='personaje'),
        ),
    ]
