# Generated by Django 4.1.7 on 2023-03-14 21:05

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invocadore_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, default=django.db.models.fields.NOT_PROVIDED, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=django.db.models.fields.NOT_PROVIDED, max_length=30)),
                ('correo', models.EmailField(default=django.db.models.fields.NOT_PROVIDED, max_length=254)),
                ('consulta', models.IntegerField(choices=[[0, 'Queja'], [1, 'Sugerencia'], [2, 'Quiero ponerme en contacto con el creador amen'], [3, 'Felicitaciones']], default=django.db.models.fields.NOT_PROVIDED)),
                ('mensaje', models.TextField(default=django.db.models.fields.NOT_PROVIDED)),
                ('avisos', models.BooleanField(default=django.db.models.fields.NOT_PROVIDED)),
            ],
        ),
    ]
