# Generated by Django 4.1.7 on 2023-03-16 16:43

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_invocadore_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invocadore',
            name='img',
            field=models.ImageField(default=django.db.models.fields.NOT_PROVIDED, upload_to='personaje'),
        ),
    ]
